anchor_version = "0.24.2"

[features]
seeds = false

[programs.mainnet]
#amm_v3 = "CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK"

[programs.devnet]
amm_v3 = "2nR3829G7xE4UE48G5Z3j38wmSJRNq624r3vpnNwHwx4"

[registry]
url = "https://github.com/alphabatem/raydium-amm-v3-2022"

[provider]
cluster = "https://billowing-purple-haze.solana-devnet.quiknode.pro/ea3ee1962c14f0c07f1524930fd6bc014290b601/"
wallet = "/home/scott/.config/solana/id.json"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./external-programs/spl_token_metadata.so"